# Generated by Django 4.1.3 on 2022-12-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planets',
            old_name='surface',
            new_name='surface_water',
        ),
    ]
