# Generated by Django 4.1.3 on 2022-12-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0003_alter_people_birth_year_alter_people_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.PROTECT, to='ex09.planets'),
        ),
    ]
